/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Entidades.Alumnos;
import Entidades.Paises;
import Entidades.Tipodocumentos;
import Persistencia.AlumnosJpaController;
import Persistencia.EmfSingleton;
import Persistencia.PaisesJpaController;
import Persistencia.TipodocumentosJpaController;
import Persistencia.exceptions.NonexistentEntityException;
import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class formCrud extends javax.swing.JFrame {
    
    AlumnosJpaController CAlumnos= new AlumnosJpaController();
    PaisesJpaController CPaises= new PaisesJpaController();
    TipodocumentosJpaController CTipoDoc= new TipodocumentosJpaController();
    List<Alumnos> alumnos;
    Alumnos alumno;
    Alumnos alumnoEdit;
    Paises paises;
    Tipodocumentos tipoDocumento;
    EntityManagerFactory emf = EmfSingleton.getInstancia().getEmf();
    EntityManager em;
    
    
    public formCrud() {
        initComponents();
        llenarTabla();
        llenarPaises();
        llenarTipoDoc();
    }
    
    public void llenarPaises(){
        em = emf.createEntityManager();
        Iterator it = em.createNamedQuery("Paises.findAll").getResultList().iterator();
        while(it.hasNext()){
            this.jComboBoxPaises.addItem((Paises) it.next());
        }
    }
    public void llenarTipoDoc(){
        em = emf.createEntityManager();
        Iterator it = em.createNamedQuery("Tipodocumentos.findAll").getResultList().iterator();
        while(it.hasNext()){
            this.jComboBoxDocument.addItem((Tipodocumentos) it.next());
        }
    }
    public void llenarTabla(){
        String [] nombres= {"ID", "Nombre", "Apellido", "DNI", "Email", "Celular", "Tipo de Documento", "Pais"};
        Object [] datos=null;
        DefaultTableModel dtm= new DefaultTableModel(null, nombres);
        alumnos= CAlumnos.findAlumnosEntities();
        for (int i = 0; i < alumnos.size(); i++) {
            dtm.addRow(datos);
            dtm.setValueAt(alumnos.get(i).getIdalumno(), i,0);
            dtm.setValueAt(alumnos.get(i).getNombre(), i,1);
            dtm.setValueAt(alumnos.get(i).getApellido(), i,2);
            dtm.setValueAt(alumnos.get(i).getDni(), i,3);
            dtm.setValueAt(alumnos.get(i).getEmail(), i,4);
            dtm.setValueAt(alumnos.get(i).getCelular(), i,5);
            dtm.setValueAt(alumnos.get(i).getIdtipodocumento().getTipodocumento(), i,6);
            dtm.setValueAt(alumnos.get(i).getIdtiponacionalidad().getNombre(), i,7);
            }
        jtabla.setModel(dtm);
    }
    private void llenarCampos(){
        try {
            //int select = jtabla.getSelectedRow();
            jTextNombre.setText(alumnos.get(jtabla.getSelectedRow()).getNombre());
            jTextApellido.setText(alumnos.get(jtabla.getSelectedRow()).getApellido());
            jTextDNI.setText(String.valueOf(alumnos.get(jtabla.getSelectedRow()).getDni()));
            jTextEmail.setText(alumnos.get(jtabla.getSelectedRow()).getEmail());
            jTextCelular.setText(alumnos.get(jtabla.getSelectedRow()).getCelular());
            jComboBoxDocument.setSelectedItem(alumnos.get(jtabla.getSelectedRow()).getIdtipodocumento());
            jComboBoxPaises.setSelectedItem(alumnos.get(jtabla.getSelectedRow()).getIdtiponacionalidad());
            //alumnoEdit= (Alumnos) jtabla.getValueAt(jtabla.getSelectedRow(), 0);
            //ver esto ultimo y como funciona el edit            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    private void vaciarCampos(){
        jTextNombre.setText("");
        jTextApellido.setText("");
        jTextDNI.setText("");
        jTextEmail.setText("");
        jTextCelular.setText("");
        jComboBoxDocument.setSelectedItem(null);
        jComboBoxPaises.setSelectedItem(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabla = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonAgregar = new javax.swing.JButton();
        botonActualizar = new javax.swing.JButton();
        botonBorrar = new javax.swing.JButton();
        botonListar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jTextApellido = new javax.swing.JTextField();
        jTextDNI = new javax.swing.JTextField();
        jTextEmail = new javax.swing.JTextField();
        jTextCelular = new javax.swing.JTextField();
        jComboBoxPaises = new javax.swing.JComboBox<>();
        jComboBoxDocument = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtabla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtabla);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setText("Nombre");

        botonAgregar.setText("Agregar");
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });

        botonActualizar.setText("Actualizar");
        botonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarActionPerformed(evt);
            }
        });

        botonBorrar.setText("Borrar");
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });

        botonListar.setText("Listar");
        botonListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListarActionPerformed(evt);
            }
        });

        jLabel2.setText("Apellido");

        jLabel3.setText("DNI");

        jLabel4.setText("Email");

        jLabel5.setText("Celular");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextNombre)
                            .addComponent(jTextApellido)
                            .addComponent(jTextDNI)
                            .addComponent(jTextEmail)
                            .addComponent(jTextCelular, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(botonAgregar)
                                .addGap(18, 18, 18)
                                .addComponent(botonActualizar)
                                .addGap(18, 18, 18)
                                .addComponent(botonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botonListar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jComboBoxPaises, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jComboBoxDocument, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxPaises, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxDocument, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAgregar)
                    .addComponent(botonActualizar)
                    .addComponent(botonBorrar)
                    .addComponent(botonListar)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        if (jTextNombre.getText().equals("") || jTextApellido.getText().equals("") || jTextDNI.getText().equals("")
            || jTextEmail.getText().equals("") || jTextCelular.getText().equals("") || jComboBoxDocument.getSelectedItem() == null 
            || jComboBoxPaises.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Debe rellenar todos los campos");
        } else {
            try {
                tipoDocumento= new Tipodocumentos();
                paises= new Paises();
                String nombre = jTextNombre.getText();
                String apellido = jTextApellido.getText();
                int dni = Integer.parseInt(jTextDNI.getText());
                String email = jTextEmail.getText();
                String celular = jTextCelular.getText();
                String idtipodocumento = (String) jComboBoxDocument.getSelectedItem();
                String idtiponacionalidad = (String) jComboBoxPaises.getSelectedItem();
                tipoDocumento.setTipodocumento(idtipodocumento); 
                paises.setNombre(idtiponacionalidad);
                CTipoDoc.create(tipoDocumento);
                CPaises.create(paises);
                alumno = new Alumnos(nombre, apellido, dni, email, celular, tipoDocumento, paises);
                CAlumnos.create(alumno);
                JOptionPane.showMessageDialog(null, "Registro exitoso");
            } catch (HeadlessException | NumberFormatException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
        llenarTabla();
        vaciarCampos();
    }//GEN-LAST:event_botonAgregarActionPerformed

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        if (jtabla.getSelectedRow() >= 0) {
            try {
                CAlumnos.destroy(alumnos.get(jtabla.getSelectedRow()).getIdalumno());
                JOptionPane.showMessageDialog(null, "Registro eliminado con exito");
            } catch (NonexistentEntityException | HeadlessException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una fila de la tabla");
        }

        vaciarCampos();
        llenarTabla();
    }//GEN-LAST:event_botonBorrarActionPerformed

    private void botonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarActionPerformed
        if (jTextNombre.getText().equals("") || jTextApellido.getText().equals("") || jTextDNI.getText().equals("")
                || jTextEmail.getText().equals("") || jTextCelular.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Debe rellenar todos los campos");
        } else {
            try {
                alumnoEdit= new Alumnos(Integer.parseInt(jtabla.getValueAt(jtabla.getSelectedRow(), 0).toString()));
                alumnoEdit.setIdtipodocumento((Tipodocumentos) jComboBoxDocument.getSelectedItem());
                alumnoEdit.setIdtiponacionalidad((Paises) jComboBoxPaises.getSelectedItem());
                alumnoEdit.setNombre(jTextNombre.getText());
                alumnoEdit.setApellido(jTextApellido.getText());
                alumnoEdit.setDni(Integer.parseInt(jTextDNI.getText()));
                alumnoEdit.setEmail(jTextEmail.getText());
                alumnoEdit.setCelular(jTextCelular.getText());
                CAlumnos.edit(alumnoEdit);
                JOptionPane.showMessageDialog(null, "Se editó el registro");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
        vaciarCampos();
        llenarTabla();
    }//GEN-LAST:event_botonActualizarActionPerformed

    private void botonListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListarActionPerformed
        if(jtabla.getSelectedRow()>=0){
            llenarCampos();
        }
        else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar una fila de la tabla");
        }
    }//GEN-LAST:event_botonListarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formCrud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonListar;
    private javax.swing.JComboBox<Tipodocumentos> jComboBoxDocument;
    private javax.swing.JComboBox<Paises> jComboBoxPaises;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextApellido;
    private javax.swing.JTextField jTextCelular;
    private javax.swing.JTextField jTextDNI;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTable jtabla;
    // End of variables declaration//GEN-END:variables
}
